list: list.h list.c
		gcc -DlistMain=main -std=c99 -pedantic -Wall -O3 list.c -o list
		./list

tree: tree.h tree.c
		gcc -DtreeMain=main -std=c99 -pedantic -Wall -O3 tree.c -o tree
		./tree

listP: list.h listPointer.c
		gcc -DlistMain=main -std=c99 -pedantic -Wall -O3 listPointer.c -o listP
		./listP
