.PHONY: test sketch

oxo:
	gcc -std=c99 -pedantic -Wall -O3 oxo.c display.c -lSDL2 -o oxo

triangle:
	gcc -std=c99 -pedantic -Wall -O3 triangleExtraDetails.c triangleDisp.c display.c -lSDL2 -o triangle

sketch:
	gcc -std=c99 -pedantic -Wall -O3 sketch.c display.c -lSDL2 -o sketch

draw:
	gcc -std=c99 -pedantic -Wall -O3 drawSave.c display.c -lSDL2 -o draw
