triangle: triangle.c
				gcc -std=c99 triangle.c -o triangle
input: input.c
				gcc -std=c99 input.c -o input
trianglePlus: triangleExtraDetails.c
				gcc -std=c99 triangleExtraDetails.c -o triangleExtraDetails
